# Solution Computations
This file is for internal use where we compute the solutions to the exercises. I also compute the solutions for seemingly easy exercises here to use the code later for automation of the process.

## CNN Size exercise solutions

In [2]:
import torch
import torch.nn as nn

conv = nn.Conv2d(1, 1, kernel_size=2, stride=1, padding=0, bias=False)

x = torch.tensor([
    [ 1, 0, -2, 1],
    [ 0, 1, 1, 0],
    [ 0, 1, 0, 1],
    [ -3, 4, 0, 0]
])

k = torch.tensor([
    [ 2, 1],
    [ 0, 1]
])

conv.weight.data = k.view(1, 1, 2, 2).float()

print(conv(x.view(1, 1, 4, 4).float()))




tensor([[[[ 3., -1., -3.],
          [ 2.,  3.,  3.],
          [ 5.,  2.,  1.]]]], grad_fn=<ConvolutionBackward0>)


In [7]:
conv = nn.Conv2d(1, 1, kernel_size=2, stride=2, padding=0, bias=False)
conv.weight.data = k.view(1, 1, 2, 2).float()
print(conv(x.view(1, 1, 4, 4).float()))


tensor([[[[ 3., -3.],
          [ 5.,  1.]]]], grad_fn=<ConvolutionBackward0>)


In [8]:
# PyTorch uses zero-padding by default
conv = nn.Conv2d(1, 1, kernel_size=2, stride=2, padding=1, bias=False)
conv.weight.data = k.view(1, 1, 2, 2).float()
print(conv(x.view(1, 1, 4, 4).float()))


tensor([[[[ 1., -2.,  0.],
          [ 0.,  3.,  0.],
          [-3.,  8.,  0.]]]], grad_fn=<ConvolutionBackward0>)


## Exercise 3 MLP Sizes

In [13]:
a = nn.Sequential(
    nn.Linear(10,5),
    nn.Linear(5,10),
    nn.Linear(10,5)
)

for i in a:
    print(sum(p.numel() for p in i.parameters()))

55
60
55


## Exercise 4 CNN Sizes

In [29]:
inp = torch.randn(1, 3, 100, 100)
arch = nn.Sequential(
    nn.Conv2d(3, 5, kernel_size=3),
    nn.MaxPool2d(2, stride=2),
    nn.Conv2d(5, 10, kernel_size=3, stride=1),
    nn.MaxPool2d(2, stride=2),
    nn.Conv2d(10, 5, kernel_size=3, stride=1),
    nn.Flatten(),
    nn.Linear(2205, 20),
    nn.Linear(20,10)
)

cur = inp
for num, layer in enumerate(arch):
    cur = layer(cur)
    print(f"{num+1}. Activation: {cur.shape}, Params: {sum(p.numel() for p in layer.parameters())}") 

1. Activation: torch.Size([1, 5, 98, 98]), Params: 140
2. Activation: torch.Size([1, 5, 49, 49]), Params: 0
3. Activation: torch.Size([1, 10, 47, 47]), Params: 460
4. Activation: torch.Size([1, 10, 23, 23]), Params: 0
5. Activation: torch.Size([1, 5, 21, 21]), Params: 455
6. Activation: torch.Size([1, 2205]), Params: 0
7. Activation: torch.Size([1, 20]), Params: 44120
8. Activation: torch.Size([1, 10]), Params: 210


0 5
1 4
2 2
