# Solution Computations
This file is for internal use where we compute the solutions to the exercises. I also compute the solutions for seemingly easy exercises here to use the code later for automation of the process.

## CNN Size

In [14]:
import torch
import torch.nn as nn

conv = nn.Conv2d(1, 1, kernel_size=2, stride=1, padding=0, bias=False)

x = torch.tensor([
    [ 1, 2, -1, 1],
    [ 1, 0, 1, 0],
    [ 0, 1, 0, 2],
    [ 2, 1, 0, -1]
])

k = torch.tensor([
    [ 1, 0],
    [ 2, 1]
])

conv.weight.data = k.view(1, 1, 2, 2).float()

print(conv(x.view(1, 1, 4, 4).float()))

tensor([[[[ 3.,  3.,  1.],
          [ 2.,  2.,  3.],
          [ 5.,  3., -1.]]]], grad_fn=<ConvolutionBackward0>)


In [15]:
conv = nn.Conv2d(1, 1, kernel_size=2, stride=2, padding=0, bias=False)
conv.weight.data = k.view(1, 1, 2, 2).float()
print(conv(x.view(1, 1, 4, 4).float()))


tensor([[[[ 3.,  1.],
          [ 5., -1.]]]], grad_fn=<ConvolutionBackward0>)


In [16]:
# PyTorch uses zero-padding by default
conv = nn.Conv2d(1, 1, kernel_size=2, stride=2, padding=1, bias=False)
conv.weight.data = k.view(1, 1, 2, 2).float()
print(conv(x.view(1, 1, 4, 4).float()))

tensor([[[[ 1.,  3.,  2.],
          [ 0.,  2.,  4.],
          [ 0.,  1., -1.]]]], grad_fn=<ConvolutionBackward0>)


## VGG weight count

In [17]:
import torchvision
vgg11 = torchvision.models.vgg.vgg11(pretrained=False)

print(
    f"Total number of parameters: {sum(p.numel() for p in vgg11.parameters())}")

print("\n\nParameter Overview in the backbone:")
for layer in vgg11.features:
    print(f"{layer}: {sum(p.numel() for p in layer.parameters())}")

print("\n\nParameter Ovewview in the head:")
for layer in vgg11.classifier:
    print(layer, sum(p.numel() for p in layer.parameters()))

/Users/igor/Conda/envs/csc413f23/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/igor/Conda/envs/csc413f23/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


Total number of parameters: 132863336


Parameter Overview in the backbone:
Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 1792
ReLU(inplace=True): 0
MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 0
Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 73856
ReLU(inplace=True): 0
MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 0
Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 295168
ReLU(inplace=True): 0
Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 590080
ReLU(inplace=True): 0
MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 0
Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 1180160
ReLU(inplace=True): 0
Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)): 2359808
ReLU(inplace=True): 0
MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False): 0
Conv2d(512, 512, kernel_size=