# Ex 2: Eigenvalues and Eigenvectors to matrices

Part (a) is straightforward. One needs to simply concatenate the given eigenvalues in a matrix.

In [5]:
import numpy as np

la1 = 2
la2 = 3
ev1 = np.array([1, 0])
ev2 = np.array([0, -1])

La = np.diag([la1, la2])
O = np.array([ev1, ev2])

np.matmul(np.matmul(O, La), O.T)

array([[2, 0],
       [0, 3]])

Part (b) has a catch. The eigenvectors are not normalized. So, we need to normalize them first before concatenating them in a matrix.

In [4]:
la1 = 2
la2 = 3
ev1 = np.array([1, 1])
ev2 = np.array([1, -1])

La = np.diag([la1, la2])
O = np.array([ev1, ev2])

print(np.matmul(np.matmul(O, La), np.linalg.inv(O)))
print(np.matmul(np.matmul(O, La), (O).T)/2) # Sanity check

[[ 2.5 -0.5]
 [-0.5  2.5]]
[[ 2.5 -0.5]
 [-0.5  2.5]]
1.4142135623730951


In [31]:
np.linalg.norm(ev2)

2.8284271247461903

# Ex 3: SGD w. Momentum Implementation

First, let's define an objective function, its gradient, and a starting point for the optimizer. In our case, this is simply $f(x) = x^2$ and $x_{init}$=1.


In [1]:
def objective(x):
    return x**2

def obj_grad(x):
    return 2*x

Now, we implement the actual optimizer.


In [2]:
def sgd_with_momentum(obj, grad, x_init, learning_rate, momentum, max_iter):
  x = x_init
  update = 0
  for i in range(max_iter):
    update = momentum * update - learning_rate * grad(x)
    x = x + update

    print('>%d f(%s) = %.5f' % (i, x, obj(x)))
  return x

In [3]:
sgd_with_momentum(
    objective, obj_grad, x_init=3.0, learning_rate=0.1, momentum=0.5, 
    max_iter=20
    )

>0 f(2.4) = 5.76000
>1 f(1.6199999999999999) = 2.62440
>2 f(0.9059999999999999) = 0.82084
>3 f(0.3677999999999999) = 0.13528
>4 f(0.02513999999999994) = 0.00063
>5 f(-0.15121800000000002) = 0.02287
>6 f(-0.2091534) = 0.04375
>7 f(-0.19629041999999997) = 0.03853
>8 f(-0.15060084599999995) = 0.02268
>9 f(-0.09763588979999996) = 0.00953
>10 f(-0.05162623373999997) = 0.00267
>11 f(-0.018296158961999986) = 0.00033
>12 f(0.0020281102194000047) = 0.00000
>13 f(0.011784622766219999) = 0.00014
>14 f(0.014305954486385997) = 0.00020
>15 f(0.012705429449191796) = 0.00016
>16 f(0.009364081040756336) = 0.00009
>17 f(0.005820590628387338) = 0.00003
>18 f(0.002884727296525372) = 0.00001
>19 f(0.0008398501712893144) = 0.00000


0.0008398501712893144