In [186]:
import torch
import torch.nn as nn

In [187]:
X = torch.tensor(
    [[1, 0, 2], 
     [2, 3, 0], 
     [-1, 0, 3]]).unsqueeze(0)

K = torch.tensor(
    [[1, 0],
     [1, 2]]).unsqueeze(0).unsqueeze(0)

## Solutions to (a), (b), and (c)

In [188]:
nn.functional.conv_transpose2d(X.unsqueeze(0), K, stride=2)

tensor([[[[ 1,  0,  0,  0,  2,  0],
          [ 1,  2,  0,  0,  2,  4],
          [ 2,  0,  3,  0,  0,  0],
          [ 2,  4,  3,  6,  0,  0],
          [-1,  0,  0,  0,  3,  0],
          [-1, -2,  0,  0,  3,  6]]]])

In [189]:
nn.functional.conv_transpose2d(X.unsqueeze(0), K, stride=1)

tensor([[[[ 1,  0,  2,  0],
          [ 3,  5,  2,  4],
          [ 1,  7,  9,  0],
          [-1, -2,  3,  6]]]])

## Solution to (d)
Below are some computations for verification.

In [190]:
def conv_transpose2d(input, weight, stride=1):
  # input - input of shape (C_in, H, W)
  # weight - kernel of shape (C_in, C_out, K, K)
  # stride - stride of the transposed convolutio
  # RETURNS
  # output - output of shape (C_out, H_out, W_out)
  (c_in, h_in, w_in) = X.size()
  (c2_in, c_out, k, k2) = K.size()

  assert c_in == c2_in, "Number of input channels must match"
  assert k == k2, "Kernel must be square"

  h_out = (h_in - 1) * stride + k
  w_out = (w_in - 1) * stride + k
  output = torch.zeros((c_out, h_out, w_out))

  for c_cur_in in range(c_in):
    for c_cur_out in range(c_out):
      for h in range(0, h_in):
        for w in range(0, w_in):
          output[c_cur_out, h*stride:h*stride+k, w*stride:w*stride+k] \
              += weight[c_cur_in, c_cur_out,:,:] * input[c_cur_in,h,w]

  return output

In [191]:
conv_transpose2d(X, K, stride=2)

tensor([[[ 1.,  0.,  0.,  0.,  2.,  0.],
         [ 1.,  2.,  0.,  0.,  2.,  4.],
         [ 2.,  0.,  3.,  0.,  0.,  0.],
         [ 2.,  4.,  3.,  6.,  0.,  0.],
         [-1.,  0.,  0.,  0.,  3.,  0.],
         [-1., -2.,  0.,  0.,  3.,  6.]]])

In [192]:
conv_transpose2d(X, K, stride=1)

tensor([[[ 1.,  0.,  2.,  0.],
         [ 3.,  5.,  2.,  4.],
         [ 1.,  7.,  9.,  0.],
         [-1., -2.,  3.,  6.]]])

In [193]:
X = torch.randn((2,3,3))
K = torch.randn((2,1,2,2))

In [194]:
conv_transpose2d(X, K, stride=1)

tensor([[[ 2.5196, -3.0373, -1.7501,  1.1531],
         [-0.2329, -1.2616, -1.2943,  0.5111],
         [-1.0364, -0.8051, -2.0395, -1.4085],
         [ 1.9276,  0.1688, -3.1863, -1.4459]]])

In [195]:
nn.functional.conv_transpose2d(X.unsqueeze(0), K, stride=1)

tensor([[[[ 2.5196, -3.0373, -1.7501,  1.1531],
          [-0.2329, -1.2616, -1.2943,  0.5111],
          [-1.0364, -0.8051, -2.0395, -1.4085],
          [ 1.9276,  0.1688, -3.1863, -1.4459]]]])