In [1]:
import torch
import torch.nn as nn

conv = nn.Conv2d(1, 1, kernel_size=2, stride=1, padding=0, bias=False)

x = torch.tensor([
    [ 1, 0, 1, -1],
    [ 1, 0, 1, 0],
    [ 0, 3, 0, 1],
    [ 1, -1, 0, 1]
])

k = torch.tensor([
    [ 1, 2],
    [ 0, 1]
])

conv.weight.data = k.view(1, 1, 2, 2).float()

print(conv(x.view(1, 1, 4, 4).float()))

tensor([[[[ 1.,  3., -1.],
          [ 4.,  2.,  2.],
          [ 5.,  3.,  3.]]]], grad_fn=<ConvolutionBackward0>)


In [2]:
conv = nn.Conv2d(1, 1, kernel_size=2, stride=2, padding=0, bias=False)
conv.weight.data = k.view(1, 1, 2, 2).float()
print(conv(x.view(1, 1, 4, 4).float()))

tensor([[[[ 1., -1.],
          [ 5.,  3.]]]], grad_fn=<ConvolutionBackward0>)


In [3]:
# PyTorch uses zero-padding by default
conv = nn.Conv2d(1, 1, kernel_size=2, stride=2, padding=1, bias=False)
conv.weight.data = k.view(1, 1, 2, 2).float()
print(conv(x.view(1, 1, 4, 4).float()))

tensor([[[[ 1.,  1.,  0.],
          [ 2.,  2.,  0.],
          [ 2., -1.,  1.]]]], grad_fn=<ConvolutionBackward0>)
