# Eigenvalues and Eigenvectors to matrices

Part (a) is straightforward. One needs to simply concatenate the given eigenvalues in a matrix.

In [2]:
import numpy as np

la1 = 1
la2 = 2
ev1 = np.array([np.sqrt(.5), np.sqrt(.5)])
ev2 = np.array([np.sqrt(.5), -np.sqrt(.5)])

La = np.diag([la1, la2])
O = np.array([ev1, ev2])

# Check orthogonality
print(np.dot(ev1, ev2))

np.matmul(np.matmul(O, La), O.T)

4.266421588589642e-17


array([[ 1.5, -0.5],
       [-0.5,  1.5]])

Part (b) has a catch. The eigenvectors are not normalized. So, we need to normalize them first before concatenating them in a matrix.

In [16]:
la1 = 2
la2 = 3
la3 = 4
ev1 = np.array([np.sqrt(1/3), np.sqrt(1/3), np.sqrt(1/3)])
ev2 = np.array([np.sqrt(.5), -np.sqrt(.5), 0])
ev3 = np.array([np.sqrt(1/6), np.sqrt(1/6), -np.sqrt(2/3)])

La = np.diag([la1, la2, la3])
O = np.array([ev1, ev2, ev3])

print(np.matmul(O, O.T))
print(np.matmul(np.matmul(O, La), np.linalg.inv(O)))

[[ 1.00000000e+00 -3.39032612e-18  2.15314570e-17]
 [-3.39032612e-18  1.00000000e+00  1.84419141e-17]
 [ 2.15314570e-17  1.84419141e-17  1.00000000e+00]]
[[ 3.         -0.40824829 -0.70710678]
 [-0.40824829  2.5        -0.28867513]
 [-0.70710678 -0.28867513  3.5       ]]


TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'